language: python
python:
    - '3.6'
addons:
    apt:
        update: true

notifications:
    irc: "chat.freenode.net#pdudaemon"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: false

before_install:
    - sudo apt-get install -y pep8

script:
    - pep8 --ignore=E501 .
    - ./setup.py install
    - ./share/pdudaemon-test.sh
